### ISSUE TITLE
eventCategory "Insight" makes the lambda fail

### ISSUE THREAD

**Issue by imavroukakis** [fivexl/terraform-aws-cloudtrail-to-slack#71]
Hey folks! There seems to exist an event type called `Insight` where the `userIdentity` field is not required, here is a sanitised example
```json
{
  "eventVersion": "1.09",
  "eventTime": "2025-01-02T12:44:00Z",
  "awsRegion": "eu-west-1",
  "eventID": "XXXXXXXX",
  "eventType": "AwsCloudTrailInsight",
  "recipientAccountId": "XXXXXX",
  "sharedEventID": "XX-XX-XX-XX-XXXXX",
  "insightDetails": {
    "state": "End",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "DescribeRegions",
    "insightType": "ApiErrorRateInsight",
    "errorCode": "Client.RequestLimitExceeded",
    "insightContext": {
      "statistics": {
        "baseline": {
          "average": 154.063788119
        },
        "insight": {
          "average": 3574.5950413223
        },
        "insightDuration": 121,
        "baselineDuration": 10723
      },
      "attributions": [
        {
          "attribute": "userIdentityArn",
          "insight": [
            {
              "value": "arn:aws:sts::XXXXX",
              "average": 3574.5950413223
            }
          ],
          "baseline": [
            {
              "value": "arn:aws:sts::XXXXX",
              "average": 154.063788119
            }
          ]
        },
        {
          "attribute": "userAgent",
          "insight": [
            {
              "value": "xxxx",
              "average": 3574.5950413223
            }
          ],
          "baseline": [
            {
              "value": "xxxx",
              "average": 154.063788119
            }
          ]
        }
      ]
    }
  },
  "eventCategory": "Insight"
}
```
As you can see, there is no `userIdentity` field to key off from so the lambda blows up with 
![image](https://github.com/user-attachments/assets/b3c08140-2bd3-432a-acc8-f6fcb1f2e45f)

**Comment by EreminAnton** [comment]
Hello! 
I looked into the issue, and there were indeed a few places where we assumed that `userIdentity` was always present. I’ve already committed a fix to the repository, but I’ll release it together with the fixes for other issues you created.

**Comment by imavroukakis** [comment]
excellent news, thanks!

**Comment by imavroukakis** [comment]
Hi folks, sorry to reopen this but we are still getting failures for logs containing `"eventCategory": "Insight"`  😢

**Comment by imavroukakis** [comment]
@EreminAnton actually it's now slightly different, it's blowing up on `eventName` not being where it expects. Maybe it would be better to ignore everything with `      "eventCategory": "Insight"` ?

**Comment by EreminAnton** [comment]
Hello! Sorry that

**Comment by EreminAnton** [comment]
Hello @imavroukakis! Sorry that the answer took so long. I've looked into the issue, and this time, the solution will not be as straightforward as it was before. This time we have ~ 50 places where we use `event[eventName]` directly. Maybe indeed ignoring all `"eventCategory": "Insight"` will be a better solution. I will discuss it with the team.

<img width="864" alt="Image" src="https://github.com/user-attachments/assets/0842e6c8-aaaf-421f-9dc1-fb95e20dd07b" />
